### ISSUE TITLE
Add new `generate.functions.FractionalSum`

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/open-estimate#32]
Related to PR #31. Maybe needed to progress on Labor projections.

_This issue is continuing a post by @jrising in https://github.com/ClimateImpactLab/open-estimate/pull/31#issuecomment-621043424:_

> While I have no problem with us having a Product calculation, I think there are still reasons to prefer a `FractionalSum` calculation object: you avoid the 1 - X problem, you can check that the fraction has no units and stays within bounds, the formatted code can be cleaner and the argument types more informative. But the partial derivative of a FractionalSum is a Sum of a FractionalSum and a Product, so you would still need to have this Product class anyway.

The goal here is to talk about whether it's needed, what's needed to make it work and what this thing might look like in the interface.

**Comment by brews** [comment]
Okay, @jrising, what are you thinking on how to handle the 1 - X problem, and bound checks with a `FractionalSum`.

What does the signature looking like to you?

The yaml from our initial discussion:

```
timerate: day
climate: [ tasmax, tasmax_rcspline ]
models:
  - csvvs: social/parameters/labor/csvv_spline_jan2020_corrected/*.csvv
    specifications:
      minlost_hi:
        csvv-subset: 1 - 12
        functionalform: cubicspline
        prefix: tasmax_rcspline
        variable: tasmax
      minlost_lo:
        csvv-subset: 13 - 24
        functionalform: cubicspline
        prefix: tasmax_rcspline
        variable: tasmax
      riskshare:
        csvv-subset: 25 - 30
        ...
    calculation:
      - FractionProduct:
          - YearlyAverageDay:
              riskshare
          - YearlyAverageDay:
              minlost_hi
          - YearlyAverageDay:
              minlost_lo
      - Rebase
```
